[build]
  command = "pip install -r requirements.txt && npm run build:next"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"
  PIP_CACHE_DIR = "/opt/buildhome/.cache/pip"

# Functions configuration for serverless functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirects for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
