[build]
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-python"

[dev]
  command = "npm run dev"
  port = 3003
  publish = ".next"
