[build]
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  port = 3003
  publish = ".next"
