[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"

# Install edge-tts during build process
[build.processing]
  skip_processing = false

# Functions configuration for serverless functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirects for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
