-- ============================================
-- TEST SIMILARITY SCORES FOR PAYMENT FAILURE QUERY
-- This helps us understand what threshold to use
-- ============================================

-- First, let's see what transcripts exist about payment failures
SELECT 
  id,
  speaker,
  LEFT(message, 100) as message_preview,
  room_name,
  org_name,
  created_at
FROM transcripts
WHERE org_name = 'hero_test'
  AND (
    message ILIKE '%payment%'
    OR message ILIKE '%failure%'
    OR message ILIKE '%gateway%'
    OR message ILIKE '%credit card%'
  )
ORDER BY created_at DESC;

-- This shows all transcripts that mention payment-related keywords
-- Check if the Sept 20 meeting transcripts appear here

-- ============================================
-- Next, check total transcript count per meeting
-- ============================================

SELECT 
  m.room_name,
  m.started_at::date as meeting_date,
  COUNT(t.id) as transcript_count,
  COUNT(t.embedding) as embedded_count,
  STRING_AGG(DISTINCT t.speaker, ', ') as speakers
FROM meetings m
LEFT JOIN transcripts t ON m.id = t.meeting_id
WHERE m.org_name = 'hero_test'
GROUP BY m.room_name, m.started_at
ORDER BY m.started_at DESC;

-- This shows all meetings and their transcript counts
-- Look for the Sept 20 meeting

-- ============================================
-- Check embedding status
-- ============================================

SELECT 
  COUNT(*) as total_transcripts,
  COUNT(embedding) as with_embeddings,
  COUNT(*) - COUNT(embedding) as missing_embeddings
FROM transcripts
WHERE org_name = 'hero_test';

-- Expected: All should have embeddings now

-- ============================================
-- MANUAL SIMILARITY TEST (Optional)
-- ============================================
-- Note: To test actual similarity scores, you would need to:
-- 1. Generate an embedding for your query: "do you know anything about payment failures"
-- 2. Run the search_transcripts_by_similarity function with different thresholds
-- 
-- The function is already created, but we need the actual query embedding
-- which is generated by Hugging Face API in the application
-- ============================================

